'use strict';

/**
 * Runs both scenarios and writes what actually happened to disk:
 *
 *   traces/broken.json   traces/fixed.json   web/traces.js
 *
 * The browser simulator replays these. Committing them means the page works on
 * a fresh clone with nothing installed and nothing running — but they are
 * recordings of a real connection, and `npm run capture` regenerates them.
 */

const fs = require('fs');
const path = require('path');
const { main } = require('./raw-repro');

const ROOT = path.join(__dirname, '..');

async function capture() {
    const results = await main({ modes: ['broken', 'fixed'], quiet: true });

    const meta = {
        capturedAt: new Date().toISOString(),
        nodeVersion: process.version,
        platform: `${process.platform} ${process.arch}`,
    };

    fs.mkdirSync(path.join(ROOT, 'traces'), { recursive: true });

    for (const [mode, result] of Object.entries(results)) {
        const trace = { ...meta, ...result };
        fs.writeFileSync(
            path.join(ROOT, 'traces', `${mode}.json`),
            JSON.stringify(trace, null, 2) + '\n'
        );
        console.log(
            `  traces/${mode}.json  —  ${result.steps.length} steps, follow-up: ${result.outcome.statusLine}`
        );
    }

    // Same data as a plain script tag, so web/index.html opens straight from
    // the filesystem without a server and without fetch() hitting CORS.
    const bundle = {
        meta,
        broken: results.broken,
        fixed: results.fixed,
    };

    fs.writeFileSync(
        path.join(ROOT, 'web', 'traces.js'),
        '/* Generated by `npm run capture` — real bytes from a real connection. */\n' +
            'window.__TRACES = ' +
            JSON.stringify(bundle, null, 2) +
            ';\n'
    );
    console.log('  web/traces.js       —  embedded for the browser simulator');
}

if (require.main === module) {
    console.log('\nCapturing real traces...\n');
    capture()
        .then(() => {
            console.log('\nDone.\n');
            process.exit(0);
        })
        .catch((err) => {
            console.error(err);
            process.exit(1);
        });
}

module.exports = { capture };
