/* Generated by `npm run capture` — real bytes from a real connection. */
window.__TRACES = {
  "meta": {
    "capturedAt": "2026-07-25T06:33:33.311Z",
    "nodeVersion": "v22.20.0",
    "platform": "linux x64"
  },
  "broken": {
    "mode": "broken",
    "reusedDirtySocket": true,
    "owedBytes": 25,
    "steps": [
      {
        "t": 1,
        "kind": "socket:opened",
        "actor": "upstream",
        "detail": "sock-1 opened (proxy → upstream (pooled))",
        "socketId": "sock-1"
      },
      {
        "t": 2,
        "kind": "client:send",
        "actor": "client",
        "detail": "user sends \"Hello\""
      },
      {
        "t": 2,
        "kind": "proxy:forward-partial",
        "actor": "proxy",
        "detail": "forwarded headers + 20 of 45 body bytes",
        "socketId": "sock-1",
        "bytes": "POST /chat-stream HTTP/1.1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 45\r\nConnection: keep-alive\r\n\r\n{\"message\":\"Hello\",\"",
        "owedBytes": 25
      },
      {
        "t": 4,
        "kind": "upstream:request-headers",
        "actor": "upstream",
        "detail": "POST /chat-stream"
      },
      {
        "t": 63,
        "kind": "client:abort",
        "actor": "client",
        "detail": "user sends a follow-up; browser aborts the first request"
      },
      {
        "t": 63,
        "kind": "proxy:abandon-upstream",
        "actor": "proxy",
        "detail": "upstream request abandoned but never destroyed — socket returns to the pool",
        "socketId": "sock-1",
        "owedBytes": 25
      },
      {
        "t": 63,
        "kind": "pool:state",
        "actor": "pool",
        "detail": "sock-1 marked idle (still owes 25 body bytes)",
        "socketId": "sock-1",
        "owedBytes": 25,
        "healthy": false
      },
      {
        "t": 123,
        "kind": "client:send",
        "actor": "client",
        "detail": "user sends \"How are you?\""
      },
      {
        "t": 123,
        "kind": "pool:checkout",
        "actor": "pool",
        "detail": "pool reuses sock-1 — it looks idle, but it is mid-message",
        "socketId": "sock-1",
        "owedBytes": 25
      },
      {
        "t": 123,
        "kind": "proxy:forward",
        "actor": "proxy",
        "detail": "forwarded the follow-up (181 bytes)",
        "socketId": "sock-1",
        "bytes": "POST /chat-stream HTTP/1.1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 52\r\nConnection: keep-alive\r\n\r\n{\"message\":\"How are you?\",\"sessionId\":\"sess-a1b2c3\"}"
      },
      {
        "t": 123,
        "kind": "upstream:steals-bytes",
        "actor": "upstream",
        "detail": "parser is still owed 25 body bytes for request #1 — it takes them from the front of request #2",
        "socketId": "sock-1",
        "owedBytes": 25,
        "stolen": "POST /chat-stream HTTP/1.",
        "resyncRemainder": "1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 52\r\nConnection: keep-alive\r\n\r\n{\"message\":\"How are you?\",\"sessionId\":\"sess-a1b2c3\"}",
        "stitchedBody": "{\"message\":\"Hello\",\"POST /chat-stream HTTP/1."
      },
      {
        "t": 124,
        "kind": "upstream:parse-error",
        "actor": "upstream",
        "detail": "HPE_INVALID_METHOD — refusing the request"
      },
      {
        "t": 125,
        "kind": "upstream:bad-body",
        "actor": "upstream",
        "detail": "body was not valid JSON (45 bytes): \"{\\\"message\\\":\\\"Hello\\\",\\\"POST /chat-stream HTTP/1.\""
      },
      {
        "t": 128,
        "kind": "socket:closed",
        "actor": "upstream",
        "detail": "sock-1 closed",
        "socketId": "sock-1"
      },
      {
        "t": 128,
        "kind": "client:error",
        "actor": "client",
        "detail": "HTTP/1.1 400 Bad Request",
        "bytes": "HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n"
      }
    ],
    "sockets": {
      "sock-1": {
        "id": "sock-1",
        "label": "proxy → upstream (pooled)",
        "openedAt": 1784961212412,
        "closedAt": 1784961212540,
        "frames": [
          {
            "dir": "out",
            "at": 1784961212414,
            "bytes": "POST /chat-stream HTTP/1.1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 45\r\nConnection: keep-alive\r\n\r\n{\"message\":\"Hello\",\""
          },
          {
            "dir": "out",
            "at": 1784961212535,
            "bytes": "POST /chat-stream HTTP/1.1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 52\r\nConnection: keep-alive\r\n\r\n{\"message\":\"How are you?\",\"sessionId\":\"sess-a1b2c3\"}"
          },
          {
            "dir": "in",
            "at": 1784961212539,
            "bytes": "HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n"
          }
        ]
      }
    },
    "outcome": {
      "statusLine": "HTTP/1.1 400 Bad Request",
      "ok": false,
      "raw": "HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n",
      "endedBecause": "socket closed",
      "tokensReceived": 0
    }
  },
  "fixed": {
    "mode": "fixed",
    "reusedDirtySocket": false,
    "owedBytes": 25,
    "steps": [
      {
        "t": 1,
        "kind": "socket:opened",
        "actor": "upstream",
        "detail": "sock-2 opened (proxy → upstream (pooled))",
        "socketId": "sock-2"
      },
      {
        "t": 2,
        "kind": "client:send",
        "actor": "client",
        "detail": "user sends \"Hello\""
      },
      {
        "t": 2,
        "kind": "proxy:forward-partial",
        "actor": "proxy",
        "detail": "forwarded headers + 20 of 45 body bytes",
        "socketId": "sock-2",
        "bytes": "POST /chat-stream HTTP/1.1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 45\r\nConnection: keep-alive\r\n\r\n{\"message\":\"Hello\",\"",
        "owedBytes": 25
      },
      {
        "t": 3,
        "kind": "upstream:request-headers",
        "actor": "upstream",
        "detail": "POST /chat-stream"
      },
      {
        "t": 62,
        "kind": "client:abort",
        "actor": "client",
        "detail": "user sends a follow-up; browser aborts the first request"
      },
      {
        "t": 63,
        "kind": "proxy:destroy-upstream",
        "actor": "proxy",
        "detail": "proxyReq.destroy() — upstream request torn down, socket leaves the pool",
        "socketId": "sock-2"
      },
      {
        "t": 63,
        "kind": "pool:state",
        "actor": "pool",
        "detail": "sock-2 destroyed",
        "socketId": "sock-2",
        "owedBytes": 0,
        "healthy": true
      },
      {
        "t": 63,
        "kind": "upstream:parse-error",
        "actor": "upstream",
        "detail": "HPE_INVALID_EOF_STATE — refusing the request"
      },
      {
        "t": 66,
        "kind": "upstream:request-aborted",
        "actor": "upstream",
        "detail": "inbound request aborted before the body finished"
      },
      {
        "t": 66,
        "kind": "socket:closed",
        "actor": "upstream",
        "detail": "sock-2 closed",
        "socketId": "sock-2"
      },
      {
        "t": 123,
        "kind": "client:send",
        "actor": "client",
        "detail": "user sends \"How are you?\""
      },
      {
        "t": 123,
        "kind": "socket:opened",
        "actor": "upstream",
        "detail": "sock-3 opened (proxy → upstream (fresh))",
        "socketId": "sock-3"
      },
      {
        "t": 124,
        "kind": "pool:checkout",
        "actor": "pool",
        "detail": "pool has no idle socket — dialled a fresh one (sock-3)",
        "socketId": "sock-3"
      },
      {
        "t": 124,
        "kind": "proxy:forward",
        "actor": "proxy",
        "detail": "forwarded the follow-up (181 bytes)",
        "socketId": "sock-3",
        "bytes": "POST /chat-stream HTTP/1.1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 52\r\nConnection: keep-alive\r\n\r\n{\"message\":\"How are you?\",\"sessionId\":\"sess-a1b2c3\"}"
      },
      {
        "t": 124,
        "kind": "upstream:request-headers",
        "actor": "upstream",
        "detail": "POST /chat-stream"
      },
      {
        "t": 124,
        "kind": "upstream:stream-open",
        "actor": "upstream",
        "detail": "streaming 9 tokens for \"How are you?\""
      },
      {
        "t": 527,
        "kind": "upstream:stream-complete",
        "actor": "upstream",
        "detail": "sent all 9 tokens"
      },
      {
        "t": 529,
        "kind": "client:ok",
        "actor": "client",
        "detail": "HTTP/1.1 200 OK",
        "bytes": "HTTP/1.1 200 OK\r\ncontent-type: text/event-stream\r\ncache-control: no-cache, no-transform\r\nconnection: keep-alive\r\nDate: Sat, 25 Jul 2026 06:33:32 GMT\r\nTransfer-Encoding: chunked\r\n\r\n15\r\ndata: {\"token\":\"I\"}\n\n\r\n16\r\ndata: {\"token\":\"'m\"}\n\n\r\n1a\r\ndata: {\"token\":\" doing\"}\n\n\r\n19\r\ndata: {\"token\":\" well\"}\n\n\r\n15\r\ndata: {\"token\":\",\"}\n\n\r\n1b\r\ndata: {\"token\":\" thanks\"}\n\n\r\n18\r\ndata: {\"token\":\" for\"}\n\n\r\n1b\r\ndata: {\"token\":\" asking\"}\n\n\r\n15\r\ndata: {\"token\":\".\"}\n\n\r\ne\r\ndata: [DONE]\n\n\r\n0\r\n\r\n"
      },
      {
        "t": 530,
        "kind": "socket:closed",
        "actor": "upstream",
        "detail": "sock-3 closed",
        "socketId": "sock-3"
      }
    ],
    "sockets": {
      "sock-2": {
        "id": "sock-2",
        "label": "proxy → upstream (pooled)",
        "openedAt": 1784961212661,
        "closedAt": 1784961212726,
        "frames": [
          {
            "dir": "out",
            "at": 1784961212662,
            "bytes": "POST /chat-stream HTTP/1.1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 45\r\nConnection: keep-alive\r\n\r\n{\"message\":\"Hello\",\""
          }
        ]
      },
      "sock-3": {
        "id": "sock-3",
        "label": "proxy → upstream (fresh)",
        "openedAt": 1784961212783,
        "closedAt": 1784961213190,
        "frames": [
          {
            "dir": "out",
            "at": 1784961212784,
            "bytes": "POST /chat-stream HTTP/1.1\r\nHost: 127.0.0.1:44847\r\nContent-Type: application/json\r\nContent-Length: 52\r\nConnection: keep-alive\r\n\r\n{\"message\":\"How are you?\",\"sessionId\":\"sess-a1b2c3\"}"
          },
          {
            "dir": "in",
            "at": 1784961212828,
            "bytes": "HTTP/1.1 200 OK\r\ncontent-type: text/event-stream\r\ncache-control: no-cache, no-transform\r\nconnection: keep-alive\r\nDate: Sat, 25 Jul 2026 06:33:32 GMT\r\nTransfer-Encoding: chunked\r\n\r\n15\r\ndata: {\"token\":\"I\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961212866,
            "bytes": "16\r\ndata: {\"token\":\"'m\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961212906,
            "bytes": "1a\r\ndata: {\"token\":\" doing\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961212946,
            "bytes": "19\r\ndata: {\"token\":\" well\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961212986,
            "bytes": "15\r\ndata: {\"token\":\",\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961213027,
            "bytes": "1b\r\ndata: {\"token\":\" thanks\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961213067,
            "bytes": "18\r\ndata: {\"token\":\" for\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961213108,
            "bytes": "1b\r\ndata: {\"token\":\" asking\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961213147,
            "bytes": "15\r\ndata: {\"token\":\".\"}\n\n\r\n"
          },
          {
            "dir": "in",
            "at": 1784961213189,
            "bytes": "e\r\ndata: [DONE]\n\n\r\n0\r\n\r\n"
          }
        ]
      }
    },
    "outcome": {
      "statusLine": "HTTP/1.1 200 OK",
      "ok": true,
      "raw": "HTTP/1.1 200 OK\r\ncontent-type: text/event-stream\r\ncache-control: no-cache, no-transform\r\nconnection: keep-alive\r\nDate: Sat, 25 Jul 2026 06:33:32 GMT\r\nTransfer-Encoding: chunked\r\n\r\n15\r\ndata: {\"token\":\"I\"}\n\n\r\n16\r\ndata: {\"token\":\"'m\"}\n\n\r\n1a\r\ndata: {\"token\":\" doing\"}\n\n\r\n19\r\ndata: {\"token\":\" well\"}\n\n\r\n15\r\ndata: {\"token\":\",\"}\n\n\r\n1b\r\ndata: {\"token\":\" thanks\"}\n\n\r\n18\r\ndata: {\"token\":\" for\"}\n\n\r\n1b\r\ndata: {\"token\":\" asking\"}\n\n\r\n15\r\ndata: {\"token\":\".\"}\n\n\r\ne\r\ndata: [DONE]\n\n\r\n0\r\n\r\n",
      "endedBecause": "stream complete",
      "tokensReceived": 9
    }
  }
};
